# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        docker build -t test-framework .
      displayName: 'Build Docker image'
    - script: |
        docker run --rm \
          -e BROWSERSTACK_USERNAME="$(BROWSERSTACK_USERNAME)" \
          -e BROWSERSTACK_ACCESS_KEY="$(BROWSERSTACK_ACCESS_KEY)" \
          -e BLOB_STORAGE_ADD_SAS_TOKEN="$(BLOB_STORAGE_ADD_SAS_TOKEN)" \
          -e BLOB_STORAGE_DELETE_SAS_TOKEN="$(BLOB_STORAGE_DELETE_SAS_TOKEN)" \
          test-framework
      displayName: 'Run tests'
      env:
        BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
        BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)
        BLOB_STORAGE_ADD_SAS_TOKEN: $(BLOB_STORAGE_ADD_SAS_TOKEN)
        BLOB_STORAGE_DELETE_SAS_TOKEN: $(BLOB_STORAGE_DELETE_SAS_TOKEN)

- task: PowerShell@2
  displayName: "Add Link to Build Summary"
  inputs:
    targetType: 'inline'
    script: |
      # Add link to build summary
      $reportUrl = "https://cosmosreports.blob.core.windows.net/automationreports/hybridtests/allure-report/index.html"
      Write-Host "##vso[task.addattachment type=Distributedtask.Core.Summary;name=Test Results Report]$reportUrl"